opyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by taking the diffs of each variant's vendor repos

## jflter970 blobs
R970_INSTALL := install/r970

PRODUCT_COPY_FILES += \
    vendor/samsung/jflter970/proprietary/bin/efsks:$(R970_INSTALL)/bin/efsks \
    vendor/samsung/jflter970/proprietary/bin/ks:$(R970_INSTALL)/bin/ks \
    vendor/samsung/jflter970/proprietary/bin/qcks:$(R970_INSTALL)/bin/qcks \
    vendor/samsung/jflter970/proprietary/lib/libreference-ril.so:$(R970_INSTALL)/lib/libreference-ril.so \
    vendor/samsung/jflter970/proprietary/lib/libril.so:$(R970_INSTALL)/lib/libril.so \
    vendor/samsung/jflter970/proprietary/lib/libsec-ril.so:$(R970_INSTALL)/lib/libsec-ril.so \
    vendor/samsung/jflter970/proprietary/vendor/lib/libqmi.so:$(R970_INSTALL)/vendor/lib/libqmi.so \
    vendor/samsung/jflter970/proprietary/vendor/lib/libqmiservices.so:$(R970_INSTALL)/vendor/lib/libqmiservices.so


## jfltespr blobs
SPR_INSTALL := install/spr

PRODUCT_COPY_FILES += \
    vendor/samsung/jfltespr/proprietary/bin/efsks:$(SPR_INSTALL)/bin/efsks \
    vendor/samsung/jfltespr/proprietary/bin/ks:$(SPR_INSTALL)/bin/ks \
    vendor/samsung/jfltespr/proprietary/bin/qcks:$(SPR_INSTALL)/bin/qcks \
    vendor/samsung/jflter970/proprietary/lib/libreference-ril.so:$(SPR_INSTALL)/lib/libreference-ril.so \
    vendor/samsung/jflter970/proprietary/lib/libril.so:$(SPR_INSTALL)/lib/libril.so \
    vendor/samsung/jflter970/proprietary/lib/libsec-ril.so:$(SPR_INSTALL)/lib/libsec-ril.so \
    vendor/samsung/jflter970/proprietary/vendor/lib/libqmi.so:$(SPR_INSTALL)/vendor/lib/libqmi.so \
    vendor/samsung/jflter970/proprietary/vendor/lib/libqmiservices.so:$(SPR_INSTALL)/vendor/lib/libqmiservices.so


## jfltevzw blobs
VZW_INSTALL :=  install/vzw

PRODUCT_COPY_FILES += \
    vendor/samsung/jfltevzw/proprietary/bin/efsks:$(VZW_INSTALL)/bin/efsks \
    vendor/samsung/jfltevzw/proprietary/bin/ks:$(VZW_INSTALL)/bin/ks \
    vendor/samsung/jfltevzw/proprietary/bin/qcks:$(VZW_INSTALL)/bin/qcks \
    vendor/samsung/jflter970/proprietary/lib/libreference-ril.so:$(VZW_INSTALL)/lib/libreference-ril.so \
    vendor/samsung/jflter970/proprietary/lib/libril.so:$(VZW_INSTALL)/lib/libril.so \
    vendor/samsung/jflter970/proprietary/lib/libsec-ril.so:$(VZW_INSTALL)/lib/libsec-ril.so \
    vendor/samsung/jflter970/proprietary/vendor/lib/libqmi.so:$(VZW_INSTALL)/vendor/lib/libqmi.so \
    vendor/samsung/jflter970/proprietary/vendor/lib/libqmiservices.so:$(VZW_INSTALL)/vendor/lib/libqmiservices.so \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.b00:$(VZW_INSTALL)/etc/firmware/q6.b00 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.b01:$(VZW_INSTALL)/etc/firmware/q6.b01 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.b03:$(VZW_INSTALL)/etc/firmware/q6.b03 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.b04:$(VZW_INSTALL)/etc/firmware/q6.b04 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.b05:$(VZW_INSTALL)/etc/firmware/q6.b05 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.b06:$(VZW_INSTALL)/etc/firmware/q6.b06 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/q6.mdt:$(VZW_INSTALL)/etc/firmware/q6.mdt \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/vidc.b00:$(VZW_INSTALL)/etc/firmware/vidc.b00 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/vidc.b01:$(VZW_INSTALL)/etc/firmware/vidc.b01 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/vidc.b02:$(VZW_INSTALL)/etc/firmware/vidc.b02 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/vidc.b03:$(VZW_INSTALL)/etc/firmware/vidc.b03 \
    vendor/samsung/jfltevzw/proprietary/etc/firmware/vidc.mdt:$(VZW_INSTALL)/etc/firmware/vidc.mdt


## Common CDMA blobs for jf
PRODUCT_COPY_FILES += \
    vendor/samsung/jfltevzw/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/jfltevzw/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/jfltevzw/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/jfltevzw/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/jfltevzw/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/jfltevzw/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/jfltevzw/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/jfltevzw/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/samsung/jfltevzw/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/jfltevzw/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/jfltevzw/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so

